[tool.poetry]
name = "prefect_docker"
version = "2.4.3"
description = "Workflow for metadata ingestion into Dataverse"
authors = ["Fjodor van Rijsselberg"]

[tool.poetry.dependencies]
python = "^3.9"
prefect = "^2.14.13"
python-dotenv = "^1.0.0"
boto3 = "^1.34.14"
dynaconf = "^3.1.11"
jmespath = "^1.0.1"
pydantic = "^2.5.3"
pydataverse = "^0.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
